# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c867f1af88225320dc96a57f4ca7d3e79ec60207852ffa3c57f5336863873da65242906d7d7598e9c14942cc4fa03b18a03e05c9fc44e6832b7035953266d424

test:
  secret_key_base: a4a7629ee240e1855b47952431bb9657b3e05211134a9b1e52f60ed01cfe8746dbe34c6c35db2f2fb25e20637046a7592c4840c1b68fe6fffa721d32f0f0de46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
